/*
 * RTE.h
 *
 *  Created on: Apr 13, 2026
 *      Author: nsist
 */

#ifndef HEADLAMP_RTE_RTE_H_
#define HEADLAMP_RTE_RTE_H_

#include "cmsis_os2.h"
#include "stm32h7xx_nucleo.h"

#include "../Application/Application.h"
#include "../HAL/HAL_Control.h"
#include "RTE_Types.h"


#define RTE_Read_LED_Status() RTE_Read_Light_Control_LED_Status()
#define RTE_Write_LED_Status(val) RTE_Write_Light_HAL_LED_Status(val)
#define RTE_Call_Set_LED(val, status) RTE_Call_Light_Control_To_HALL_Set_LED(val, status)
#define RTE_Call_Get_LED(val) RTE_CALL_Light_Control_To_Hall_Get_LED(val)

#define Light_Functionality_POS_DRL_Command(val) 	RTE_Call_LightApp_LightControl_Light_Func_DRL_POS_Command(val)
#define Light_Functionality_Low_Beam_Command(val) 			RTE_Call_LightApp_LightControl_Light_Func_LowBeam_Command(val)
#define Light_Functionality_High_Beam_Command(val)	RTE_Call_LightApp_LightControl_Light_Func_HighBeam_Command(val)
#define Light_Functionality_TI_Hazzard_Command(val)	RTE_Call_LightApp_LightControl_Light_Func_TI_Hazzard_Command(val)
#define Light_Functionality_FOG_Command(val)				RTE_Call_LightApp_LightControl_Light_Func_FOG_Command(val)
#define RTE_Call_Send_Motor_Position(val) RTE_Call_MotorApp_MotorControl_Command_Position(val)

#define RTE_Write_Light_Command_Rotary_Switch_Value(val) RTE_Write_CommandControl_CommandApp_Light_Command_Rotary_Switch_Value(val)
#define RTE_Write_Leveling_Pot_Value(val) RTE_Write_CommandControl_CommandApp_Leveling_Pot_Value(val)
#define RTE_Write_R_Blinker_Button_Value(val) RTE_Write_CommandControl_CommandApp_R_Blinker_Button_Value(val)
#define RTE_Write_L_Blinker_Button_Value(val) RTE_Write_CommandControl_CommandApp_L_Blinker_Button_Value(val)
#define RTE_Write_Hazzard_Button_Value(val) RTE_Write_CommandControl_CommandApp_Hazzard_Button_Value(val)
#define RTE_Write_HighBeam_Button_Value(val) RTE_Write_CommandControl_CommandApp_HighBeamButon_Value(val)
#define RTE_Write_Light_Command_Switch_Position(val) RTE_Write_CommandApp_LightApp_Light_Command_Switch_Position(val)
#define RTE_Write_Blinker_Command_State(val) RTE_Write_CommandApp_LightApp_Blinker_Command_State(val)
#define RTE_Write_High_Beam_Command_State(val) RTE_Write_CommandApp_LightApp_HighBeam_Command(val)
#define RTE_Write_Leveling_Command_Value(val) RTE_Write_CommandApp_MotorApp_Leveling_Command_Value(val)
#define RTE_Write_HeadLamp_Temp(val) RTE_Write_FanApp_LightApp_HeadLamp_Temp(val)
#define RTE_Write_Sensor_Temp(val) RTE_Write_Sensor_FanApp_Temperature_Read_Value(val)
#define RTE_Write_Sensor_Angle(val) RTE_Write_Sensor_MotorApp_Sensor_Angle(val)
#define RTE_Write_FanSpeed(val) RTE_Write_FanApp_FanControl_FanSpeed(val)
#define RTE_Write_Light_Control_Init_Done(val) RTE_Write_LightControl_LightApp_InitDone(val)
#define RTE_Write_HighBeam_Pot_Control_Level(val) RTE_Write_CommandApp_LightApp_HighBeam_Pot_Control_Level(val)
#define RTE_Write_Ambiental_Luminosity(val) RTE_Write_SensorControl_LightApp_Ambiental_Luminosity(val)
#define RTE_Write_Motor_Command_Auto(val) RTE_Write_LightApp_MotorApp_Motor_Command_Auto(val)
#define RTE_Write_Increase_FanSpeed_HighBeam(val) RTE_Write_LightApp_FanApp_Increase_FanSpeed_HighBeam(val)
#define RTE_Write_HighBeam_Pot_Control_Value(val) RTE_Write_SensorControl_CommandApp_HighBeam_Pot_Control_Value(val)

#define RTE_Read_Light_Command_Rotary_Switch_Value() RTE_Read_CommandApp_CommandControl_Light_Command_Rotary_Switch_Value()
#define RTE_Read_Leveling_Pot_Value() RTE_Read_CommandApp_Command_Control_Leveling_Pot_Value()
#define RTE_Read_R_Blinker_Button_Value() RTE_Read_CommandApp_Command_Control_R_Blinker_Button_Value()
#define RTE_Read_L_Blinker_Button_Value() RTE_Read_CommandApp_Command_Control_L_Blinker_Button_Value()
#define RTE_Read_Hazzard_Button_Value() RTE_Read_CommandApp_Command_Control_Hazzard_Button_Value()
#define RTE_Read_HighBeam_Button_Value() RTE_Read_CommandApp_Command_Control_HighBeamButon_Value()
#define RTE_Read_Light_Command_Switch_Position() RTE_Read_LightApp_CommandApp_Light_Command_Switch_Position()
#define RTE_Read_Blinker_Command_State() RTE_Read_LightApp_CommandApp_Blinker_Command_State()
#define RTE_Read_HighBeam_Command_State() RTE_Read_LightApp_CommandApp_HighBeam_Command_State()
#define RTE_Read_HeadLamp_Temp() RTE_Read_LightApp_FanApp_HeadLamp_Temp()
#define RTE_Read_Leveling_Command_Value() RTE_Read_CommandApp_MotorApp_Leveling_Command_Value()
#define RTE_Read_Sensor_Temp() Rte_Read_FanApp_Sensor_Sensor_Temp()
#define RTE_Read_FanSpeed() RTE_Read_FanControl_FanApp_FanSpeed()
#define RTE_Read_Light_Control_Init_Done() RTE_Read_LightControl_LightApp_InitDone()
#define RTE_Read_HighBeam_Pot_Control_Level() RTE_Read_CommandApp_LightApp_HighBeam_Pot_Control_Level()
#define RTE_Read_Ambiental_Luminosity() RTE_Read_SensorControl_LightApp_Ambiental_Luminosity()
#define RTE_Read_Motor_Command_Auto() RTE_Read_LightApp_MotorApp_Motor_Command_Auto()
#define RTE_Read_Increase_FanSpeed_HighBeam() RTE_Read_LightApp_FanApp_Increase_FanSpeed_HighBeam()
#define RTE_Read_HighBeam_Pot_Control_Value() RTE_Read_SensorControl_CommandApp_HighBeam_Pot_Control_Value()

uint8_t RTE_Read_Light_Control_LED_Status();
bool RTE_Internal_Read_LED(void);
void RTE_Call_Light_Control_To_HALL_Set_LED(Led_TypeDef LED, uint8_t status);
uint8_t RTE_CALL_Light_Control_To_Hall_Get_LED(Led_TypeDef LED);

void RTE_Write_CommandControl_CommandApp_Light_Command_Rotary_Switch_Value(uint8_t val);
void RTE_Write_CommandControl_CommandApp_Leveling_Pot_Value(uint8_t val);
void RTE_Write_CommandControl_CommandApp_R_Blinker_Button_Value(bool val);
void RTE_Write_CommandControl_CommandApp_L_Blinker_Button_Value(bool val);
void RTE_Write_CommandControl_CommandApp_Hazzard_Button_Value(bool val);
void RTE_Write_CommandControl_CommandApp_HighBeamButon_Value(bool val);
void RTE_Write_CommandApp_LightApp_Light_Command_Switch_Position(s_Light_Func_Comm val);
void RTE_Write_CommandApp_LightApp_Blinker_Command_State(s_Blink_Func_Comm val);
void RTE_Write_CommandApp_LightApp_HighBeam_Command(bool val);
void RTE_Write_CommandApp_MotorApp_Leveling_Command_Value(uint16_t val);
void RTE_Write_FanApp_LightApp_HeadLamp_Temp(uint8_t val);
void RTE_Write_Sensor_FanApp_Temperature_Read_Value(uint8_t val);
void RTE_Write_Sensor_MotorApp_Sensor_Angle(uint8_t val);
void RTE_Write_FanApp_FanControl_FanSpeed(uint8_t val);
void RTE_Write_LightControl_LightApp_InitDone(bool val);
void RTE_Write_CommandApp_LightApp_HighBeam_Pot_Control_Level(uint8_t val);
void RTE_Write_SensorControl_LightApp_Ambiental_Luminosity(uint8_t val);
void RTE_Write_LightApp_MotorApp_Motor_Command_Auto(bool val);
void RTE_Write_LightApp_FanApp_Increase_FanSpeed_HighBeam(bool val);
void RTE_Write_SensorControl_CommandApp_HighBeam_Pot_Control_Value(uint16_t val);

void RTE_Call_LightApp_LightControl_Light_Func_DRL_POS_Command(s_Light_Pixel_PWM_Command val);
void RTE_Call_LightApp_LightControl_Light_Func_LowBeam_Command(uint8_t val);
void RTE_Call_LightApp_LightControl_Light_Func_HighBeam_Command(s_Light_Pixel_PWM_Command val);
void RTE_Call_LightApp_LightControl_Light_Func_TI_Hazzard_Command(s_Light_Pixel_PWM_Command val);
void RTE_Call_LightApp_LightControl_Light_Func_FOG_Command(uint8_t val);
void RTE_Call_MotorApp_MotorControl_Command_Position(uint8_t val);

uint8_t RTE_Read_CommandApp_CommandControl_Light_Command_Rotary_Switch_Value();
uint8_t RTE_Read_CommandApp_Command_Control_Leveling_Pot_Value();
bool RTE_Read_CommandApp_Command_Control_R_Blinker_Button_Value();
bool RTE_Read_CommandApp_Command_Control_L_Blinker_Button_Value();
bool RTE_Read_CommandApp_Command_Control_Hazzard_Button_Value();
bool RTE_Read_CommandApp_Command_Control_HighBeamButon_Value();
s_Light_Func_Comm RTE_Read_LightApp_CommandApp_Light_Command_Switch_Position();
s_Blink_Func_Comm RTE_Read_LightApp_CommandApp_Blinker_Command_State();
uint8_t RTE_Read_LightApp_FanApp_HeadLamp_Temp();
uint16_t RTE_Read_CommandApp_MotorApp_Leveling_Command_Value();
bool RTE_Read_LightApp_CommandApp_HighBeam_Command_State();
uint8_t RTE_Read_FanApp_Sensor_Temperature_Read_Value();
uint8_t RTE_Read_MotorApp_Sensor_Sensor_Angle();
uint8_t RTE_Read_FanControl_FanApp_FanSpeed();
bool RTE_Read_LightControl_LightApp_InitDone();
uint8_t RTE_Read_CommandApp_LightApp_HighBeam_Pot_Control_Level();
uint8_t RTE_Read_SensorControl_LightApp_Ambiental_Luminosity();
bool RTE_Read_LightApp_MotorApp_Motor_Command_Auto();
bool RTE_Read_LightApp_FanApp_Increase_FanSpeed_HighBeam();
uint16_t RTE_Read_SensorControl_CommandApp_HighBeam_Pot_Control_Value();

void init();
void cyclic_task_10ms();
void cyclic_task_20ms();
void cyclic_task_50ms();


#endif /* HEADLAMP_RTE_RTE_H_ */
