/*
 * Command_App.h
 *
 * Created on: Apr 27, 2026
 * Author: nsist
 */

#ifndef HEADLAMP_APPLICATION_COMMANDS_APP_CONTROLS_INCLUDE_COMMAND_APP_H_
#define HEADLAMP_APPLICATION_COMMANDS_APP_CONTROLS_INCLUDE_COMMAND_APP_H_

void Init_Command_App(void);
void Run_Command_App_Main_20ms(void);

#endif /* HEADLAMP_APPLICATION_COMMANDS_APP_CONTROLS_INCLUDE_COMMAND_APP_H_ */